### ISSUE TITLE
Render another template from inside a template

### ISSUE THREAD

**Issue by wildlingdev** [Tyrrrz/MiniRazor#1]
First and foremost, great work here! nice compact library, with a pleasant API surface area!

As I start to dig in, the first thing that presents itself is the need to support more complex layout, and most project contributors will obviously be familiar with the asp.net mvc's method for doing so.

These pieces are missing from the basic examples given so far ... is there another method built-in for templating in MiniRazor?

**Comment by Tyrrrz** [comment]
I think this is still valuable for run-time templates and should be available through a method on `ITemplate`. Additionally, we should probably add in some capacity to the build-time templates flow for consistency purposes, even though the approach shown above is simpler and more efficient.

**Comment by Tyrrrz** [comment]
Descoped as I'm archiving the project
