### ISSUE TITLE
Transitive assembly loading is too eager

### ISSUE THREAD

**Issue by unsprung** [Tyrrrz/MiniRazor#14]
I ran into an issue with a .Net 5 project using MiniRazor that also references [ZXing.Net](https://github.com/micjahn/ZXing.Net). 

I am not really sure where the fault lies, but while loading transitive dependencies, MiniRazor is attempting to load a reference to "PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" that I found out is referenced by ZXing.Net. 

Our .Net 5 project is referencing the .Net Standard 2.0 version of ZXing.Net which doesn't seems to have any "active" references to PresentationCore, or at least not for the functionality we are using. GetReferencedAssemblies as part of Compile in MiniRazor returns the PresentationCore reference though, and MiniRazor attempts to load it.

Does it make sense to include an overload or configuration option in MiniRazor that would allow a consumer to specify a list of references to ignore/exclude, to be able to work around situation like this? I could perhaps provide a PR if we can agree on a suitable solution.

**Comment by Tyrrrz** [comment]
I think the best way is probably to make this method overload public:

https://github.com/Tyrrrz/MiniRazor/blob/73fd19a63117a579517a3f8545c4ed18f3f9e3fe/MiniRazor.Compiler/Razor.cs#L130-L134

That way you can provide your own references. The default behavior is indeed too eager, it tries to resolve all references that the executing assembly has. I don't know of a way to make this smarter.

By the way, is build-time compilation not usable for your scenario?
