### ISSUE TITLE
C# versioning error when using in .NET Standard 2.0 project.

### ISSUE THREAD

**Issue by JackScottAU** [Tyrrrz/MiniRazor#18]
### Version

ver 2.2.1

### Details

I'm using MiniRazor within a .NET Standard 2.0 project (as this is the maximum version allowed to reference this project from a UWP project). Using compile-time template generation yields the following error:

`Feature 'nullable reference types' is not available in C# 7.3. Please use language version 8.0 or greater.`

The NuGet package listing seems to indicate this package is compatible with .NET Standard 2.0.

### Steps to reproduce

- Create a new .NET Standard 2.0 project.
- Install the MiniRazor Nuget package.
- Create a Razor template and set it be built at compile time as per documentation.
- Observe error message on build.

**Comment by Tyrrrz** [comment]
You can use higher versions of C# with older target frameworks, you just might not have access to all the features. In your `csproj`, add this property:

```xml
<Project>

  <PropertyGroup>
    <!-- ... -->
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
```

**Comment by JackScottAU** [comment]
Thanks, that worked!
