### ISSUE TITLE
Support compile to dll

### ISSUE THREAD

**Issue by wzxinchen** [Tyrrrz/MiniRazor#19]
### Details

Can you support compiling to DLL files? I checked the source code and found that the contents of the DLL already exist, but you got the type from the DLL and returned it.

**Comment by wzxinchen** [comment]
I fork a source code and add a method, but I hope the author can support it

**Comment by Tyrrrz** [comment]
It's not in scope, sorry. It's easier to just use the raw Razor bindings to achieve that.
