### ISSUE TITLE
Option to remove insignificant whitespace

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/MiniRazor#2]
To make the output file smaller, it would be nice to be able to optionally remove insignificant whitespace. This would only work with HTML but theoretically Razor could be used for any type of output, so maybe consider some more generic solution?

**Comment by jzabroski** [comment]
What do you consider insignificant whitespace?  Is this insignificant?

```html
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
```

or do you just mean things like indentation via space char, `\t`, '\n\r` and '\n'.  For the last two, you need to consider that the assembly could have been compiled/saved on Windows with Windows' style Environment.NewLine (e.g., AzureDevOps currently uses Windows Data Center Edition 2019), but run on a Linux machine (in the Azure cloud).

**Comment by Tyrrrz** [comment]
@jzabroski that's a good point.
I was thinking insignificant whitespace as in between tags like:

```
<a>foo</a>    <p>bar</p>
-------------[^^]
insignificant whitespace
```

However, with [`white-space: pre-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) this gets really murky.

**Comment by Tyrrrz** [comment]
Decided it's out of scope because of too many variables involved. Wanna keep this library compact and simple to stay true to the "Mini" in "MiniRazor".

**Comment by jzabroski** [comment]
@Tyrrrz  Agreed. 

Also, in researching this just now, it seems like .NET doesn't have a good open source wrapper for HTML Tidy.  The TidyManaged package on Nuget.org was last updated in 2015, and is a .NET Framework 2.0 assembly, so it is iffy if it would work on .NET Core.

Seems like a decent side project to get something up for .NET.  Honestly, HtmlAgilityPack solves most my problems, but it doesn't handle semantic stuff like this:

> ```xml
> <a>foo</a>    <p>bar</p>
> ----------[^^]
> insignificant whitespace
> ```
