### ISSUE TITLE
Separate codegen package to avoid dependency on Razor compilation libraries

### ISSUE THREAD

**Issue by ignatandrei** [Tyrrrz/MiniRazor#6]
I do not  Razor as a dependency when adding the reference , right ? 
But I need MiniRazor.TemplateBase as a reference
Could you put MiniRazor.TemplateBase in a separate project ? 
This way I can do

<PackageReference Include="MiniRazorBaseClasse" Version="2.0.x" />

<PackageReference Include="MiniRazor" Version="2.0.x" PrivateAssets="all"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer"/>
    
to not reference Razor when dot net publish

**Comment by Tyrrrz** [comment]
Sorry, I'm not sure what you're asking exactly.
If you are _only_ using MiniRazor for build-time template compilation, you can most likely just mark it as a private dependency via `PrivateAssets="all"`.

**Comment by ignatandrei** [comment]
If I do this, when publish, it says that is missing Razor library. Because it is used in TemplateBase....

**Comment by Tyrrrz** [comment]
Makes sense, `PrivateAssets="all"` won't work.
